### ISSUE TITLE
Custom PCB for electronics

### ISSUE THREAD

**Issue by Zergie** [Zergie/YAMMU#17]
- [x] Design and Publish Schematics and EasyEDA link
- [x] Add DIN Rail Mount for the PCB
- [x] Add Gerber files
- [x] Add Files for PCB Assembly

**Comment by Zergie** [comment]
![image](https://github.com/user-attachments/assets/033d7eff-2b8e-4cd3-8fa8-1942a65beefa)

Work in Progress ... waiting for pcb to arrive.

Know Bug, already :(
- no header for BLDC (2x PWM, 2x Tacho)

**Comment by Zergie** [comment]
It seems I cannot get serial over USB working :( I tried three STM32F103C8T6 boards with the same result. All of them work when connected via CH340 serial breakout board using UART over USB. [This](https://www.aliexpress.com/item/1005006833541219.html?spm=a2g0o.order_list.order_list_main.10.3cdd1802y11ezP) [] is the  model (APM32F103CBT6 TYPE-C) I use.

Flashed the MSC bootloader with ST-Link:
https://www.klipper3d.org/Bootloaders.html#stm32f103stm32f072-with-msc-bootloader

Compiled klipper mcu with:
![image](https://github.com/user-attachments/assets/b83682ce-3b58-4857-9e9d-96372c6c8afb)

Copied that over to the STM32 via the provided usb flash drive.

When connected to the Raspberry Pi, it is recognized:
![image](https://github.com/user-attachments/assets/e4e6dd77-2712-4e98-be30-86628fc2c6c4)

But when using this config:
printer.cfg
```
[include fluidd.cfg]
[include stm32.cfg]

[virtual_sdcard]
path: /home/user/printer_data/gcodes
on_error_gcode: CANCEL_PRINT

[respond]
default_type: echo

[printer]
kinematics: none
max_velocity: 100
max_accel: 100
```
stm32.cfg
```
[mcu]
serial: /dev/serial/by-id/usb-Klipper_stm32f103xe_B55B5A1A00000000260DF001-if00
#baud: 115200
restart_method: command

[temperature_sensor STM32F103]
sensor_type: temperature_mcu
sensor_mcu: mcu

[fan_generic MF1]
pin: mcu:PB3
```

I get this error:
![image](https://github.com/user-attachments/assets/c49f1a57-b0a4-4e9a-83fc-95820caa408c)

klippy.log
```
Build file /home/user/klipper/klippy/../.config(3668): Fri Oct 11 12:07:14 2024
========= Last MCU build config =========
CONFIG_LOW_LEVEL_OPTIONS=y
# CONFIG_MACH_AVR is not set
# CONFIG_MACH_ATSAM is not set
# CONFIG_MACH_ATSAMD is not set
# CONFIG_MACH_LPC176X is not set
CONFIG_MACH_STM32=y
# CONFIG_MACH_HC32F460 is not set
# CONFIG_MACH_RP2040 is not set
# CONFIG_MACH_PRU is not set
# CONFIG_MACH_AR100 is not set
# CONFIG_MACH_LINUX is not set
# CONFIG_MACH_SIMU is not set
CONFIG_BOARD_DIRECTORY="stm32"
CONFIG_MCU="stm32f103xe"
CONFIG_CLOCK_FREQ=72000000
CONFIG_USBSERIAL=y
CONFIG_FLASH_SIZE=0x10000
CONFIG_FLASH_BOOT_ADDRESS=0x8000000
CONFIG_RAM_START=0x20000000
CONFIG_RAM_SIZE=0x5000
CONFIG_STACK_SIZE=512
CONFIG_FLASH_APPLICATION_ADDRESS=0x8002000
CONFIG_STM32_SELECT=y
CONFIG_MACH_STM32F103=y
# CONFIG_MACH_STM32F207 is not set
# CONFIG_MACH_STM32F401 is not set
# CONFIG_MACH_STM32F405 is not set
# CONFIG_MACH_STM32F407 is not set
# CONFIG_MACH_STM32F429 is not set
# CONFIG_MACH_STM32F446 is not set
# CONFIG_MACH_STM32F765 is not set
# CONFIG_MACH_STM32F031 is not set
# CONFIG_MACH_STM32F042 is not set
# CONFIG_MACH_STM32F070 is not set
# CONFIG_MACH_STM32F072 is not set
# CONFIG_MACH_STM32G070 is not set
# CONFIG_MACH_STM32G071 is not set
# CONFIG_MACH_STM32G0B0 is not set
# CONFIG_MACH_STM32G0B1 is not set
# CONFIG_MACH_STM32G431 is not set
# CONFIG_MACH_STM32G474 is not set
# CONFIG_MACH_STM32H723 is not set
# CONFIG_MACH_STM32H743 is not set
# CONFIG_MACH_STM32H750 is not set
# CONFIG_MACH_STM32L412 is not set
# CONFIG_MACH_N32G452 is not set
# CONFIG_MACH_N32G455 is not set
# CONFIG_MACH_STM32F103x6 is not set
CONFIG_MACH_STM32F1=y
CONFIG_HAVE_STM32_USBFS=y
CONFIG_HAVE_STM32_CANBUS=y
# CONFIG_STM32F103GD_DISABLE_SWD is not set
CONFIG_STM32_DFU_ROM_ADDRESS=0
CONFIG_STM32_FLASH_START_2000=y
# CONFIG_STM32_FLASH_START_5000 is not set
# CONFIG_STM32_FLASH_START_7000 is not set
# CONFIG_STM32_FLASH_START_8000 is not set
# CONFIG_STM32_FLASH_START_8800 is not set
# CONFIG_STM32_FLASH_START_9000 is not set
# CONFIG_STM32_FLASH_START_10000 is not set
# CONFIG_STM32_FLASH_START_800 is not set
# CONFIG_STM32_FLASH_START_1000 is not set
# CONFIG_STM32_FLASH_START_4000 is not set
# CONFIG_STM32_FLASH_START_0000 is not set
CONFIG_STM32_CLOCK_REF_8M=y
# CONFIG_STM32_CLOCK_REF_12M is not set
# CONFIG_STM32_CLOCK_REF_16M is not set
# CONFIG_STM32_CLOCK_REF_20M is not set
# CONFIG_STM32_CLOCK_REF_24M is not set
# CONFIG_STM32_CLOCK_REF_25M is not set
# CONFIG_STM32_CLOCK_REF_INTERNAL is not set
CONFIG_CLOCK_REF_FREQ=8000000
CONFIG_STM32F0_TRIM=16
CONFIG_STM32_USB_PA11_PA12=y
# CONFIG_STM32_SERIAL_USART1 is not set
# CONFIG_STM32_SERIAL_USART1_ALT_PB7_PB6 is not set
# CONFIG_STM32_SERIAL_USART2 is not set
# CONFIG_STM32_SERIAL_USART2_ALT_PD6_PD5 is not set
# CONFIG_STM32_SERIAL_USART3 is not set
# CONFIG_STM32_SERIAL_USART3_ALT_PD9_PD8 is not set
# CONFIG_STM32_CANBUS_PA11_PA12 is not set
# CONFIG_STM32_CANBUS_PA11_PB9 is not set
# CONFIG_STM32_MMENU_CANBUS_PB8_PB9 is not set
# CONFIG_STM32_MMENU_CANBUS_PD0_PD1 is not set
CONFIG_USB=y
CONFIG_USB_VENDOR_ID=0x1d50
CONFIG_USB_DEVICE_ID=0x614e
CONFIG_USB_SERIAL_NUMBER_CHIPID=y
CONFIG_USB_SERIAL_NUMBER="12345"

#
# USB ids
#
# end of USB ids

CONFIG_WANT_GPIO_BITBANGING=y
CONFIG_WANT_DISPLAYS=y
CONFIG_WANT_SENSORS=y
CONFIG_WANT_LIS2DW=y
CONFIG_WANT_LDC1612=y
CONFIG_WANT_HX71X=y
CONFIG_WANT_ADS1220=y
CONFIG_WANT_SOFTWARE_I2C=y
CONFIG_WANT_SOFTWARE_SPI=y
CONFIG_NEED_SENSOR_BULK=y
CONFIG_CANBUS_FREQUENCY=1000000
CONFIG_INITIAL_PINS=""
CONFIG_HAVE_GPIO=y
CONFIG_HAVE_GPIO_ADC=y
CONFIG_HAVE_GPIO_SPI=y
CONFIG_HAVE_GPIO_I2C=y
CONFIG_HAVE_GPIO_HARD_PWM=y
CONFIG_HAVE_STRICT_TIMING=y
CONFIG_HAVE_CHIPID=y
CONFIG_HAVE_STEPPER_BOTH_EDGE=y
CONFIG_HAVE_BOOTLOADER_REQUEST=y
CONFIG_INLINE_STEPPER_HACK=y
=======================
Build file /home/user/klipper/klippy/../out/klipper.dict(8089): Fri Oct 11 12:09:26 2024
Last MCU build version: v0.12.0-315-g8f361a15b
Last MCU build tools: gcc: (15:12.2.rel1-1) 12.2.1 20221205 binutils: (2.39-8+rpi1+18) 2.39
Last MCU build config: ADC_MAX=4095 BUS_PINS_i2c1=PB6,PB7 BUS_PINS_i2c1a=PB8,PB9 BUS_PINS_i2c2=PB10,PB11 BUS_PINS_spi1=PA6,PA7,PA5 BUS_PINS_spi1a=PB4,PB5,PB3 BUS_PINS_spi2=PB14,PB15,PB13 BUS_PINS_spi3=PB4,PB5,PB3 CLOCK_FREQ=72000000 MCU=stm32f103xe PWM_MAX=255 RESERVE_PINS_USB=PA11,PA12 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1
Build file /home/user/klipper/klippy/../out/klipper.elf(1033108): Fri Oct 11 12:10:33 2024
mcu 'mcu': Wait for identify_response
Traceback (most recent call last):
  File "/home/user/klipper/klippy/serialhdl.py", line 68, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/klipper/klippy/serialhdl.py", line 262, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/klipper/klippy/serialhdl.py", line 319, in get_response
    self.serial.raw_send_wait_ack(cmds[-1], minclock, reqclock,
  File "/home/user/klipper/klippy/serialhdl.py", line 254, in raw_send_wait_ack
    self._error("Serial connection closed")
  File "/home/user/klipper/klippy/serialhdl.py", line 61, in _error
    raise error(self.warn_prefix + (msg % params))
serialhdl.error: mcu 'mcu': Serial connection closed
```

**Comment by Zergie** [comment]
Following [[Mcu: Serial connection closed](https://klipper.discourse.group/t/mcu-serial-connection-closed-timeout-on-connect-wait-for-identify-response/6645)](https://klipper.discourse.group/t/mcu-serial-connection-closed-timeout-on-connect-wait-for-identify-response/6645)

sudo dmesg -e
![image](https://github.com/user-attachments/assets/d52a06c9-2012-4ea5-89e2-230c00112438)

lsusb -tv
```
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 480M
        ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
        |__ Port 4: Dev 11, If 0, Class=Communications, Driver=cdc_acm, 12M
            ID 1d50:614e OpenMoko, Inc.
        |__ Port 4: Dev 11, If 1, Class=CDC Data, Driver=cdc_acm, 12M
            ID 1d50:614e OpenMoko, Inc.
```

**Comment by Zergie** [comment]
Changing the baud rate as suggested [here](https://github.com/Klipper3d/klipper/issues/3047#issuecomment-656170448) does nothing.

**Comment by Zergie** [comment]
I thought it is worth the shot: [reddit](https://www.reddit.com/r/klippers/comments/rmy182/comment/hppfmop/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

But, when recompiled everything with:
![image](https://github.com/user-attachments/assets/7b486a9d-54b5-4f6f-9fd1-3905b1d0d638)

I get:
![image](https://github.com/user-attachments/assets/a51cd81a-36b3-4c1f-b915-690f3eef77dc)

So it seems "USB (on PA11/12)" should be right?

**Comment by Zergie** [comment]
Flashing with 16KiB also results in:
![image](https://github.com/user-attachments/assets/4e52ecf1-127d-4803-93ee-2173302526ae)

**Comment by Zergie** [comment]
Tested on second Raspberry Pi (BTT PI) => no serial connection :(

```
mcu 'stm32': Starting serial connect
mcu 'stm32': Timeout on connect
mcu 'stm32': Wait for identify_response
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/serialhdl.py", line 68, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
  File "/home/biqu/klipper/klippy/serialhdl.py", line 262, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
  File "/home/biqu/klipper/klippy/serialhdl.py", line 319, in get_response
    self.serial.raw_send_wait_ack(cmds[-1], minclock, reqclock,
  File "/home/biqu/klipper/klippy/serialhdl.py", line 254, in raw_send_wait_ack
    self._error("Serial connection closed")
  File "/home/biqu/klipper/klippy/serialhdl.py", line 61, in _error
    raise error(self.warn_prefix + (msg % params))
serialhdl.error: mcu 'stm32': Serial connection closed
```

**Comment by Zergie** [comment]
Seems to be the [same](https://klipper.discourse.group/t/diy-stm32f103cbt6-apm32-klipper-can-not-connect/5083/4) problem, but no usable solution.

Also tried:
![image](https://github.com/user-attachments/assets/cec4bd2b-ade6-40b8-ba76-c09f84d5bcac)

=> no success :(

**Comment by Zergie** [comment]
Flashed without boot loader and SWD:
![image](https://github.com/user-attachments/assets/a14bb426-2e9d-4de6-aba8-f39cdf7cf89e)

=> same result

**Comment by Zergie** [comment]
Trying with katapult...

1. after flashing with ST-Link
![image](https://github.com/user-attachments/assets/f39cf3c2-1490-4216-ba39-97088cd9a33c)

2. make menuconfig
![image](https://github.com/user-attachments/assets/8ffab335-ab14-4c1f-84b7-8eccb7420281)

3.
